steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: symbols-Windows
    path: $(Pipeline.Workspace)/symbols/Windows
  displayName: Download Windows symbols
  continueOnError: true

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: test_symbols-Windows
    path: $(Pipeline.Workspace)/test_symbols/Windows
  displayName: Download Windows test symbols
  continueOnError: true

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Pipeline.Workspace)/symbols
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: Publish symbols

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Pipeline.Workspace)/test_symbols
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: Publish test symbols

- powershell: azure-pipelines/Publish-Legacy-Symbols.ps1 -Path $(Pipeline.Workspace)/symbols/Windows
  displayName: Publish symbols for symbol archival
